### ISSUE TITLE
find results exception

### ISSUE THREAD

**Issue by GoEddie** [GoEddie/SSDT-DevPack#15]
System.ArgumentException: The parameter is incorrect. (Exception from HRESULT: 0x80070057 (E_INVALIDARG)) at EnvDTE._DTE.get_ActiveDocument() at SSDTDevPack.QueryCosts.Highlighter.CodeCoverageHighlightWordTagger.UpdateWordAdornments() at SSDTDevPack.QueryCosts.Highlighter.HighlightWordTagger.UpdateAtCaretPosition(CaretPosition caretPosition) at SSDTDevPack.QueryCosts.Highlighter.HighlightWordTagger.CaretPositionChanged(Object sender, CaretPositionChangedEventArgs e) at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.RaiseEvent[TArgs](Object sender, EventHandler`1 eventHandlers, TArgs args)

**Comment by GoEddie** [comment]
I fixed this with the 2017 support

**Comment by flipdoubt** [comment]
Thanks. I just installed it and will let you know of any issues.
