### ISSUE TITLE
Generate a SET IDENTITY_INSERT statement in MergeUI

### ISSUE THREAD

**Issue by bonskijr** [GoEddie/SSDT-DevPack#16]
**Issue**:
When generating a MERGE statement for tables with IDENTITY columns , SET IDENTITY_INSERT is not included in the generated script. 

**Repro**:
Add a table with identity field in MergeUI and click save, generated script doesnt have SET IDENTITY_INSERT

**Work Around:** 
Manually adding the statement

**Comment by GoEddie** [comment]
When I was originally writing it I thought about this probably a little too much! I decided that mergeui was to handle reference data which shouldn't really have an identity column as it would normally be to match enum's etc in app code.

I think for a better way to handle more complicated solutions then the tool to use is sp_generate_merge - I use that mostly and it works very well - mergeui gets used when it is simple columns etc.

sorry!
