### ISSUE TITLE
VS 2017 Support

### ISSUE THREAD

**Issue by flipdoubt** [GoEddie/SSDT-DevPack#17]
Would love to use SSDT-DevPack in VS 2017, but VS 2017 completely ignores it while VS 2015 sees it fine.

**Comment by GoEddie** [comment]
Hi,

I will do it at some point, I'm not sure what need doing, probably changing the vsix manifest to include 15.0.


Ed

**Comment by flipdoubt** [comment]
Thanks!

**Comment by flipdoubt** [comment]
Can't compile it, but I added a pull request for this issue:
https://github.com/GoEddie/SSDT-DevPack/pull/18

**Comment by flipdoubt** [comment]
Can anyone get this pull-request compiled with the 2017 target?

**Comment by Gander7** [comment]
I believe it takes more than just a target update for 2017 as discussed [here](https://docs.microsoft.com/en-us/visualstudio/extensibility/how-to-migrate-extensibility-projects-to-visual-studio-2017)

I tried opening the `src/Merge/src/SSDTDevPack.VSPackage/SSDTDevPack.VSPackage.csproj` and received a [migration error](http://imgur.com/a/bFx5R).

**Comment by GoEddie** [comment]
there is a version that can be tested: https://github.com/GoEddie/SSDT-DevPack/releases/tag/v2-beta

**Comment by GoEddie** [comment]
vs 2017 support has now been pushed to the visual studio marketplace, any comments let me know :)

https://the.agilesql.club/blogs/Ed-Elliott/2017-04-24/SSDT-DevPack-Visual-Studio-2017
