### ISSUE TITLE
What replaces MergeUI if 'Everything below this is deprecated...'

### ISSUE THREAD

**Issue by lestephane** [GoEddie/SSDT-DevPack#22]
In the visual studio tools menu for SSDT Dev Pack, the 'Everything below this is deprecated...' menu item is present, and below it, among others, is MergeUI. Does that mean MergeUI has been superseded with a better way? If so which one?

**Comment by GoEddie** [comment]
I just use sp_generate_merge and use the output from that, it works pretty well

**Comment by lestephane** [comment]
Ok thanks
